
version: '3.9'

volumes: 
  prometheus-vm:
  granafa-vm:

networks: 
  test-net:
    external: true

services: 
  prometheus:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.10'
          memory: 200M
        reservations:
          cpus: '0.05'
          memory: 50M
    
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ../prometheus/:/etc/prometheus/
      - prometheus-vm:/prometheus
    ports:
      - 9090:9090
    networks:
      - test-net

  grafana:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.10'
          memory: 200M
        reservations:
          cpus: '0.05'
          memory: 50M
    hostname: grafana
    image: grafana/grafana
    volumes:
      - granafa-vm:/var/lib/grafana
    ports:
    - 3000:3000
    networks:
      - test-net