
version: '3.9'

volumes: 
  prometheus-vm:
  granafa-vm:

networks: 
  test-net:

services: 
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-vm:/prometheus
    ports:
      - 9090:9090
    networks:
      - test-net